name: CI

on:
  push:
    branches:
      - "main"
    paths:
      - "**/*.md"
  pull_request:
    branches:
      - "main"

jobs:
  static-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
      - name: Install dependencies
        run: |
          yarn --frozen-lockfile
      - name: Spell check
        run: |
          yarn check:spell
          yarn check:lint:md

  pre-commit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
