name: CI

on:
  push:
    branches:
      - "main"
    paths:
      - "**/*.md"
  pull_request:
    branches:
      - "main"

jobs:
  static-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn
      - name: Install dependencies
        run: |
          yarn --immutable
      - name: Static check
        run: |
          yarn static-check

  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
